feat: added dynamic multiple choice validation schema
UserOfficeProject/user-office-lib pull request #162
Opened 2023-02-14 11:02 UTC by Junjiequan

## Motivation and Context

Added dynamic multiple choice validation schema
https://jira.esss.lu.se/secure/RapidBoard.jspa?rapidView=798&projectKey=SWAP&view=detail&selectedIssue=SWAP-3047

## How Has This Been Tested

* manual

## Changes

packages/validation/src/Questionary/dynamicMultipleChoice.ts

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2023-02-16 12:53 UTC, martin-trajanovski requested changes
This looks good but only thing you are missing here is to update the package version in the package-lock.json file and to do that we usually run the command `npm run lerna:prePublish` in the root.

2023-02-16 14:25 UTC, jekabs-karklins approved these changes

2023-02-21 09:12 UTC, jekabs-karklins approved these changes

2023-02-21 13:00 UTC, martin-trajanovski approved these changes

2023-02-21 13:00 UTC, merged